### ISSUE TITLE
can not find Button2.h, Int64String.h

### ISSUE THREAD

**Issue by kawashimaken** [rebane2001/chanduino#2]
I have got some compiler errors, saying that the following files are missing.
` 
#include <Button2.h>
#include <Int64String.h>
`

**Comment by kawashimaken** [comment]
Oh! thank you for your fast reply!
Actually, I just found them from GitHub, now compiling...  without errors!

**Comment by rebane2001** [comment]
I removed Int64String from the imports and added Button2 as a dependency in the README
