### ISSUE TITLE
Board location retention?

### ISSUE THREAD

**Issue by thatblend** [rebane2001/chanduino#3]
Hey anon, great project but it's kind of pain in the ass to browse boards on this since every time I go into a thread and then go back to the board it brings me back to the beginning of the board instead of where I left off. I would code it myself but I'm too much of a brainlet to even understand the code. And yes, I'm unironically using this as my main 4chan device.

**Comment by rebane2001** [comment]
The problem with this is that I don't have enough RAM to store the catalog, so when you go back I need to refresh it and when I refresh it the order changes anyways. I might be able to retain the previous order and that could work, but then it'd mean you wouldn't be able to refresh the board without leaving the board and going back (but that might be worth it for this).

**Comment by thatblend** [comment]
I think it would be worth it, most boards are slow moving anyway where you need to refresh them maybe once in 30 minutes or something and just going back to the board list and back to refresh a board doesn't take that long.

**Comment by rebane2001** [comment]
Added in bdb57938b01a1d4a7fe068d118332d2261f77050
